# Site settings
author: Joshua Williams
title: 3 Steps at a Time
header-img: img/home-bg.png
email: jmw0426@hotmail.com
copyright_name: Joshua Williams
description: > # this means to ignore newlines until "baseurl:"
  FlatIron School Software Engineering Online
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jmw0426

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
